### ISSUE TITLE
[Feature Request] Whitelist mode for Apps

### ISSUE THREAD

**Issue by nervyalloy51** [Audio4Linux/JDSP4Linux#10]
I currently use this program to filter my music while talking in voice chats.

while this is currently possible I have to add every application that is not playing music to the blocklist manually.

I would love a feature to switch to whitelist mode so that I would only need to select the music app and everything else would remain unaffected by the filter

**Comment by ThePBone** [comment]
Feature added with commit 68d323f7644fb842ca2d5c26ea071514baea3853

You can enable this mode here: Settings > Devices > Blocklisted apps
