### ISSUE TITLE
failed to install on ubuntu

### ISSUE THREAD

**Issue by iconoclasthero** [Audio4Linux/JDSP4Linux#102]
Following the Add PPA Repo from the main README.md:

```
$ cat thepbone_ppa.gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/thepbone_ppa.gpg
echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/thepbone_ppa.gpg] https://thepbone.github.io/PPA-Repository ./" > /etc/apt/sources.list.d/thepbone_ppa.list
[sudo] password for $USER: 
bash: /etc/apt/sources.list.d/thepbone_ppa.list: Permission denied
⋮
$ sudo echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/thepbone_ppa.gpg] https://thepbone.github.io/PPA-Repository ./" > /etc/apt/sources.list.d/thepbone_ppa.list
bash: /etc/apt/sources.list.d/thepbone_ppa.list: Permission denied
$ sudo sh -c ' echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/thepbone_ppa.gpg] https://thepbone.github.io/PPA-Repository ./" > /etc/apt/sources.list.d/thepbone_ppa.list '
```
I don't know for sure why the instructions didn't work for me, but I do know that the > in the echo command gets processed before the sudo at the beginning of the line which is why tee is used instead.  In order to get the sudo to apply to the redirect, it needs to be executed in a shell.  This should also work instead of a separate sudo shell:

` $ echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/thepbone_ppa.gpg] https://thepbone.github.io/PPA-Repository ./"  | sudo tee /etc/apt/sources.list.d/thepbone_ppa.list `

**Comment by ThePBone** [comment]
Thanks, I updated the readme.
