### ISSUE TITLE
jamesdsp binary in .deb files from Releases is not stripped and packed (whopping 108,8mb)

### ISSUE THREAD

**Issue by revast** [Audio4Linux/JDSP4Linux#107]
with stripping (`strip  --strip-unneeded  ./jamesdsp`), I get it down to 13,4mb, packing with [UPX](https://upx.github.io/) gets it down to 6,5mb.. still runs fine.

![image](https://user-images.githubusercontent.com/8189198/230497310-644e5f9a-a82e-4e90-9caf-7206ad399a17.png)

**Comment by ThePBone** [comment]
Thanks. Binaries in .deb packages will be stripped properly with commit 45a231729177d35b8d4dc82fd4c06345fa03141b.
