### ISSUE TITLE
[Feature Request] Graphic EQ for each channel

### ISSUE THREAD

**Issue by oversky** [Audio4Linux/JDSP4Linux#113]
Can we have independent graphic EQ for left and right channel?
For people who don't have a dedicated room to music, 
speakers are often placed asymmetric,
and result in different room reflection.
If we can EQ each channnel separately according to the measurement data, 
we will get a more balanced sound and image.
Thank you.

**Comment by oversky** [comment]
If there is no space to put dual channels in the UI,
may I suggest a separate tool to convert the csv file to impulse respone for convolution.
Thanks.

**Comment by ThePBone** [comment]
> Can we have independent graphic EQ for left and right channel?

This is a good idea, although JDSP4Linux is just a port of https://github.com/james34602/JamesDSPManager, so I'm not the original author of the algorithms and don't have a very deep understanding of them.
But I'll see if I can get it working; I added this to my to-do list, but I don't have an ETA at the moment.

> may I suggest a separate tool to convert the csv file to impulse respone for convolution.

That sounds easier to do, but then again, I don't have much knowledge about signal processing, so I would need to find some program library that implements these algorithms for me. But I'll try to stick to your first request for now.

**Comment by ThePBone** [comment]
No, the ImpResToolbox only contains algorithms to read/resample impulse responses from .wav file format and an utility function to generate an interpolated EQ graph display for the UI.
The libjamesdsp code doesn't contain anything for converting graphic eq data to an impulse response as far as I know.

**Comment by oversky** [comment]
JDSP4Linux-master\libjamesdsp\subtree\VeryOldOpen_source_edition\Audio_Engine\eclipse_libjamesdsp_free_bp\jni\ArbFIRGen.c
`double *ArbitraryEqMinimumPhase(ArbitraryEq *gains, double fs)
{
	unsigned int fLMul2 = gains->fLMul2;
	unsigned int flMul2Minus1 = fLMul2 - 1;
	kiss_fft_cpx* timeData = gains->timeData;
	kiss_fft_cpx* freqData = gains->freqData;
	kiss_fft_cfg planForward = gains->planForward;
	kiss_fft_cfg planReverse = gains->planReverse;
	// Log grid interpolation
	unsigned int i;
	for (i = 0; i < gains->filterLength; i++)
	{
		double freq = (double)i * fs / (double)fLMul2;
		double dbGain = gainAtLogGrid(gains, freq);
		double gain = pow(10.0, dbGain / 20.0);
		freqData[i].r = gain;
		freqData[i].i = 0;
		freqData[flMul2Minus1 - i].r = gain;
		freqData[flMul2Minus1 - i].i = 0;
	}
	minimumPhaseSpectrum(timeData, freqData, planForward, planReverse, gains->filterLength);
	kiss_fft(planReverse, freqData, timeData);
	double factor, *finalImpulse = gains->impulseResponse;
	for (i = 0; i < gains->filterLength; i++)
	{
		factor = 0.5 * (1.0 + cos(PI2 * (double)i / (double)fLMul2));
		finalImpulse[i] = factor / (double)fLMul2 * timeData[i].r;
	}
	return finalImpulse;
}`

ArbitraryEqMinimumPhase, return finalImpulse are the keywords to me.

https://sourceforge.net/p/equalizerapo/code/HEAD/tree/trunk/filters/GraphicEQFilter.cpp
Here is the source code of EqualizerAPO with such comment:
// Minimum phase spectrum from coefficients

Can you take a look?

**Comment by ThePBone** [comment]
The EqualizerAPO code looks right, also used by AutoEQ for creating impulse responses from similar data: https://github.com/jaakkopasanen/AutoEq/blob/75ef88f072dc39a8241d2c7a05aa6afecde59357/autoeq/frequency_response.py#L367.

Also, I was wrong, the current JDSP code does actually have this at `libjamesdsp/subtree/Main/libjamesdsp/jni/jamesdsp/jdsp/generalDSP/ArbFIRGen.c` (the path you linked is the older version).

I'll see if I can separate it into a separate utility.

**Comment by ThePBone** [comment]
I put up the new tool here: https://github.com/ThePBone/geq2imp

It supports choosing separate CSV files for the left and right channels. Check the readme for compile instructions.

**Comment by oversky** [comment]
I opend an issue in geq2imp.
Got and warning email "Issue assignment: All jobs have failed"

**Comment by ThePBone** [comment]
> Got and warning email "Issue assignment: All jobs have failed"

My mistake, I copy-and-pasted lots of stuff from this repo to the geq2imp one to save time, including some GitHub automation workflows, which caused the error.
