### ISSUE TITLE
GCC compile fails on Arch Linux

### ISSUE THREAD

**Issue by corrupteddrive** [Audio4Linux/JDSP4Linux#115]
Here's the log from my package manager:
../../src/audio/base/IOutputDevice.h:12:5: error: ‘uint32_t’ does not name a type
   12 |     uint32_t id = ((uint32_t)0xffffffff);
      |     ^~~~~~~~
../../src/audio/base/IOutputDevice.h:5:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
    4 | #include <string>
  +++ |+#include <cstdint>
    5 |
make[1]: *** [Makefile:3600: PresetManager.o] Error 1
make[1]: Leaving directory '/home/corrupted/.cache/yay/jamesdsp-git/src/JDSP4Linux/build/src'
make: *** [Makefile:73: sub-src-make_first] Error 2

**Comment by ThePBone** [comment]
Fixed. See #100
