### ISSUE TITLE
Add jamesdsp to flatpak

### ISSUE THREAD

**Issue by chicco-carone** [Audio4Linux/JDSP4Linux#119]
I was trying to use jamesdsp on my steam deck but because it's not on flatpak i had to install it via the chaotic-aur and after a few steamos updates it doesn't work anymore. If it was on flathub or a generic flatpak repo it would be easier to use on linux distros with read only file systems.

**Comment by ThePBone** [comment]
A flatpak package (Pipewire version) is now available on flathub: https://flathub.org/apps/me.timschneeberger.jdsp4linux
