### ISSUE TITLE
Can't control the sink volume at pavucontrol

### ISSUE THREAD

**Issue by Bob-YsPan** [Audio4Linux/JDSP4Linux#139]
After I update the JDSP4Linux, originally I can control the volume at pavucontrol(Also can be controlled using the shortcut key), 
but now it can't control now.

My system is Manjaro Linux (Updated few days ago).

Like the screenshot below. Although I mute or turn the volume down to 0, it seems like the sink doesn't follow the pavucontrol's control, and passthrough the full-volume audio to the JDSP and output.
![image](https://github.com/Audio4Linux/JDSP4Linux/assets/46966555/27a47aa2-6474-485b-abaf-48ff89318490)

**Comment by ThePBone** [comment]
Don't set JamesDSP as the default output device. The virtual JamesDSP sink doesn't support volume controls and using it as a default can cause other issues too.

To fix this, you just need to set your actual headphone/speakers as the default audio output device.

**Comment by Bob-YsPan** [comment]
OK, I just wonder if some application will not redirect the sound to the Jamedsp Sink so I do this setting.
I turn it back now and tries that all applications will redirect its sound to the sink or not, thanks.
