### ISSUE TITLE
JDSP crashes (SIGSEGV) upon enabling Viper DDC

### ISSUE THREAD

**Issue by Tomoms** [Audio4Linux/JDSP4Linux#14]
Hello,
I'm using openSUSE Tumbleweed, self-compiled JDSP, Pipewire.
I've opened the DDC tab, selected my vdc file, then tried to enable Viper DDC by checking its checkbox. JDSP then crashed with a segfault. Log available here: https://susepaste.org/5c33f12e
If you need me to try anything else, do let me know.

**Comment by ThePBone** [comment]
Could you please upload the VDC file that caused this crash as well?

**Comment by Tomoms** [comment]
https://drive.google.com/file/d/15LZftAevnmRHWHKPjhpr_1D95OveyGXl/view?usp=sharing
Here it is. I have found it on the 4PDA forum. It works fine in Viper4Android.

**Comment by james34602** [comment]
> https://drive.google.com/file/d/15LZftAevnmRHWHKPjhpr_1D95OveyGXl/view?usp=sharing Here it is. I have found it on the 4PDA forum. It works fine in Viper4Android.

It work fine in Viper4Android doesn't mean the filter work properly.

Number of coefficients of a IIR SOS require 5 to work properly.
Sony MH410c.vdc has 209 coefficient, which is indivisible by 5, 209 / 5 = 41.8.

We can make it "work" by padding 1 zero-value coefficient to the end, but it will most likely not reproducing the original magnitude response create by VDCToolbox.

In simple word, you VDC file is corrupt, I appreciate you provide the .vdcproj file as well.

**Comment by james34602** [comment]
@Tomoms You see below coefficients from the VDC file:
1,00375674425774,-1,99948588709588,0,995737260526334
There is no stable IIR filter that having that extreme pole-zero values.

This file is completely corrupted, the reason it work fine on Viper4Android is because Viper4Android skip the VDC processing.
