### ISSUE TITLE
fatal error: model/codecontainer.h: No such file or directory

### ISSUE THREAD

**Issue by vibo69** [Audio4Linux/JDSP4Linux#158]
```
In file included from ../../src/data/EelParser.cpp:1:
../../src/data/EelParser.h:4:10: fatal error: model/codecontainer.h: No such file or directory
    4 | #include <model/codecontainer.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:2079: EelParser.o] Error 1
```
Debian 12 (up-to-date)

**Comment by ThePBone** [comment]
This repo contains git submodules that also need to be checked out. 
The `--recursive` flag when running `git clone` normally handles that, but since you already cloned the repo, you just need to run 
```
git submodule update --init 
```
to initialize the missing submodules.

**Comment by vibo69** [comment]
submodule update was not enough.. I needed to clean everything and start over. Now it works! Thanks! :)
