### ISSUE TITLE
[Feature Request] Auto-switching presets

### ISSUE THREAD

**Issue by danildf** [Audio4Linux/JDSP4Linux#16]
Could you please consider adding an auto-switch functionality for presets based on default output device. I often switch between two different bluetooth headsets and internal speaker. Each of the headsets requires its own DDC config.

**Comment by ThePBone** [comment]
Hey,

commit c09dbe7030d270963d9a75f6e2e16296f6002e60 introduces this feature.

You can access the new menu here: `Presets > Rules... > Add`

To get the latest version that includes this new feature, get either the AUR git package (`jamesdsp-git`), download a DEB package here: https://github.com/Audio4Linux/JDSP4Linux/actions/runs/1597373412, or compile it manually.
