### ISSUE TITLE
How to check if JamesDSP is working?

### ISSUE THREAD

**Issue by jackuars7** [Audio4Linux/JDSP4Linux#167]
Hi there

I have noticed that when I try to click the bypass button, the indicator "Bypass" doesn't seem to change color or at least it's not visible. However, in the default UI, I can see that it's getting a little grey and still reads as "Bypass". I am not seeing any noticeable improvements.

I would like to know how I can check if it's working. I am trying to listen to an audiobook, and when I have Bypass selected in the vocal booster equalizer, the vocals appear to sound more feeble, I think.

I just want to know if I need to have "Bypass" checked or not, and how I can determine if JamesDSP is working.

Thank you for your assistance.

**Comment by ThePBone** [comment]
Hi, the bypass toggle button should not be checked.
While it's pressed down, JamesDSP will not modify any audio data.

It's very hard to see right now, especially when not using the default style, so I've pushed a change that will tint the whole button red when pressed (commit cec4baf).

You can check the current state using this command: `jamesdsp --get master_enable`. If it returns `true`, then JamesDSP is enabled.
