### ISSUE TITLE
Can't install JamesDSP.pulse with flatpak

### ISSUE THREAD

**Issue by Homeswinghome** [Audio4Linux/JDSP4Linux#196]
Hello,
Following the problem described in an other issue (no sound from JamesDSP on Debian12), I tried to install it on an other laptop running Ubuntu 22.04 so pulse. I installed Flatpak but at the command :
sudo flatpak install me.timschneeberger.jdsp4linux.pulse
I got
Looking for matches…
F: An error was encountered searching remote ‘thepbones-repo’ for ‘me.timschneeberger.jdsp4linux.pulse’: Unable to load summary from remote thepbones-repo: GPG verification enabled, but no summary found (check that the configured URL in remote config is correct)
error: No remote refs found similar to ‘me.timschneeberger.jdsp4linux.pulse’
Same without the "sudo"
Thank you for your help
I really would like to have JamesDSP running on my laptops, before the issues, I add the possibility to check the functionalities. Seems really great. I am interested by 2 of them : the convolver, the scripting which a unique function. 
PS : I would appreciate any input to be able to build my own wav files for the convolver. I understand it is 4 ways : LL, LR, RR, RL (maybe not this order...). I have for now only mono or stereo format like, LL, RR. Any help with Python or Audacity is welcome.

**Comment by Homeswinghome** [comment]
Hello,
Now that we understood the expected Pipewire version for JamesDSP and knowing Pipewire is the standard for the future release of Debian or Ubuntu, the solution was to remove PulseAudio and to install the latest Pipewire version from an external PPA.
JamesDSP was not installed from Flatpak but from NIX package manager along with Helvum.

**Comment by Homeswinghome** [comment]
See the workaround in the last comment.

**Comment by 01-1** [comment]
This is not a solution.
