### ISSUE TITLE
missing qtbase5-private-dev package in the list of prerequisites

### ISSUE THREAD

**Issue by sergstesh** [Audio4Linux/JDSP4Linux#197]
I tried to compile the project using instructions described in https://github.com/Audio4Linux/JDSP4Linux/blob/master/BUILD.md file. Specifically, I installed prerequisites as stated in

`sudo apt install build-essential qt6-qpa-plugins libarchive-dev qt6-base-private-dev qt6-base-dev libqt6svg6-dev libglibmm-2.4-dev libglib2.0-dev libpipewire-0.3-dev qttools5-dev-tools libgl-dev`

 .

Compilation failed with an error message stating missing qplatformnativeinterface.h file (I don't have the exact error message at the moment). After doing some web search I installed qtbase5-private-dev package, and this resolved the issue.

Please update the list of prerequisites to include the missing package.

**Comment by timschneeb** [comment]
I don't think that is required unless you are compiling using Qt 5.x instead of Qt 6.x.
Anyway, I've added it to the instructions.
