### ISSUE TITLE
Can't install jamesdsp-pulse_2.3 on kubuntu 20.2 focal and Debian 11 bullseye 

### ISSUE THREAD

**Issue by p-root** [Audio4Linux/JDSP4Linux#20]
Hi ! Thanks a lot for your great job ! :+1: 

I can't install the latest jamesdsp-pulse 2.3 release on two linux 64 systems,
Because there are **two missing dependencies** :
- libarchive is not installable for **kubuntu 20.2 focal** 
- libarchive is not installable for **Debian 11 bullseye**

But **libarchive13** is installed on both.

and

- **libgstreamer-plugins-good1.0.0** is not installable **only** for Debian 11 bullseye

Thanks a lot for your help !

**Comment by xukashi** [comment]
+1 Debian Sid

**Comment by drnick88101** [comment]
I think libarchive-dev needs to be installed instead. I also just install kubuntu and had this same problem. I was able to compile it myself after your instructions and an extra step. In order to compile it myself I had to also run this: sudo apt install build-essential


thanks for this great app. i love it!

**Comment by ThePBone** [comment]
Thanks for reporting this issue. 

I've updated the dependency list. You can download *.deb packages here, once the cloud worker has finished (~10min): https://github.com/Audio4Linux/JDSP4Linux/actions/runs/1644454296

I'll update the PPA after I test everything in a VM.

**Comment by ThePBone** [comment]
The updated packages have been pushed to the PPA; they *should* work now.

**Comment by Sush-ruta** [comment]
I tried installing `jamesdp-pipewire` from the PPA in Ubuntu 21.10 impish but I'm also getting this error.
`jamesdsp-pipewire : Depends: libarchive but it is not installable`

**Comment by ThePBone** [comment]
I fixed the issue with the PPA; I added the new fixed package but forgot to remove the old, broken package. Both packages had the same version string (v2.3), which caused confusion with the package manager.
