### ISSUE TITLE
{feature requerst] "relink audio pipeline" CLI option

### ISSUE THREAD

**Issue by 45bcdf** [Audio4Linux/JDSP4Linux#200]
I am using a headless computer to act as a dsp hub in my hifi. I am looking for a command line option for reloading JamesDSP that is equivalent to the "Reload James DSP" GUI feature. Based on my search into the CLI options I do not see one listed on Github or in the jamesdsp --help options.  Basically I am hoping there is a way I can relink the audio pipeline via the CLI without connecting to the system with a remote desktop and initiate the relink using JamesDSP's GUI. Alternatively, would initiating a --load-preset <preset> effectively re-link the audio and resolve the issue? Would this also be a reasonable workaround? 

Otherwise JamesDSP works great and has let me really optimize my system and get the most out of what is otherwise a relatively cheap hi-fi rig that sounds really good! Thanks for any help.

**Comment by timschneeb** [comment]
No, `--load-preset` doesn't relink the pipeline. As a workaround, killing and restarting the JamesDSP process would have the same effect.

I've added a `--relink` action to the CLI in commit bfdaccf4. You can either build from the master branch or download binaries here: https://github.com/Audio4Linux/JDSP4Linux/actions/runs/9906035039
