### ISSUE TITLE
Rule for wired heasdphone

### ISSUE THREAD

**Issue by magillos** [Audio4Linux/JDSP4Linux#22]
Would it be possible to alow creating a separate rule for wired headphones? Right now it's not possible, as in my laptop the speakers are fed from the same audio device.

**Comment by ThePBone** [comment]
Sure, I'll add that soon. I completely forgot about the fact that a single device can register multiple ports.

**Comment by jtl5770** [comment]
I actually stumbled upon the same when trying out if JDSP4linux could replace easyeffects for my needs - it seems the rules always apply to the whole device, while I would have the need to differentiate between e.g. headphone, laptop speakers or hdmi out).

Simliar reasoning applies to blutooth devices where I would want to differentiate between the headset profile and the hifi audio profile

**Comment by ThePBone** [comment]
This is implemented in version 2.7.0: https://github.com/Audio4Linux/JDSP4Linux/releases/tag/2.7.0
