### ISSUE TITLE
compressor fuzz/static

### ISSUE THREAD

**Issue by atomGit** [Audio4Linux/JDSP4Linux#23]
enabling the dynamic range compressor produces significant "static" in the audio stream regardless of the source (firefox, audacious, mplayer)

i don't know what triggers this, but i don't think it happened immediately after the first install, however removing ~/.config/jamesdsp and restarting the the app doesn't help

manjaro, jdsp 2.3-1 (AUR)
Server Name: PulseAudio (on PipeWire 0.3.42)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right

**Comment by james34602** [comment]
Dynamic range compression mean to whiten the dynamic range of signal, if we perform operation on frequency domain, which is the case in JDSP, we will then compress the dynamic range of every subband, that's why the song become "fuzzy", the "noisy" part is because the spectral have been heavily whitened, usually by very strong amount(High aggressiveness), the spectrum becomes white noise-liked, reduce aggressiveness is the only way to reduce the "noisy" effect.

**Comment by atomGit** [comment]
hi James 
i'm not very audio knowledgeable - what i want to achieve is system-wide volume/gain "normalization" so that all sources play at a similar volume - i did this before with EasyEffects and it involved a compressor (see [here](https://tz.liuqiufeng.com/Digitalone1/EasyEffects-Presets)), but there was no white noise/fuzz - can this be done with with JDSP?

**Comment by james34602** [comment]
I don't think any online/real time algorithm able to perform volume normalization without impact the artist-intended dynamic range, true volume normalization can be done using replay gain, any real time algorithm isn't really reliable for such task, see: [ReplayGain](https://en.wikipedia.org/wiki/ReplayGain)
`With dynamic range compression, volume may be altered on-the-fly on playback producing a variable-gain normalization, as opposed to the constant gain as rendered by ReplayGain. While dynamic range compression is beneficial in keeping volume constant, it changes the artistic intent of the recording`

**Comment by atomGit** [comment]
> ... without impact the artist-intended dynamic range

yes, i agree - i didn't fully explain;  it is not my intention to dynamically compress music - for that i use ReplayGain

what i need to do is perform volume/gain normalization when watching videos/movies in order to raise the quiet parts and suppress the really loud parts - so basically i want to create a preset that i can load when watching videos/movies, but i don't know how best to do that

**Comment by atomGit** [comment]
for any other DSP dummies like myself that happen to find this...

the Limiter/Master seems to do exactly as i wanted; it limits the max gain and boosts the min gain - my current settings, which seem to work pretty well...

threshold: -15 db (how much to reduce max volume)
release: 60 ms (not so important, but a setting between 5 and 100 ms seems to make sense)
post gain: 5 db (raises min volume/gain)

i don't really know how high post gain could be increased - if you knock 15 db off the top, can you raise post gain to +15 db? this seems logical, but then it seems there would be no difference in volume between a whisper and a gun shot - i think the settings i'm currently using provide a 10 db window in which the volume can fluctuate if i understand this correctly
