### ISSUE TITLE
"Unknown Organization" folder in ~/.config

### ISSUE THREAD

**Issue by atomGit** [Audio4Linux/JDSP4Linux#24]
the file in this folder (jamesdsp.conf) appears to contain window geometry - i'm guessing it should probably be moved to ~/.config/jamesdsp/ with the other config files

**Comment by ThePBone** [comment]
Oops, I didn't intend to save the window geometry information into a completely different config file.
Commit 66b7cb5 fixes this and stores it at: `~/.config/jamesdsp/application.conf`
