### ISSUE TITLE
Import room equalization wizard equalizer files?

### ISSUE THREAD

**Issue by kokoko3k** [Audio4Linux/JDSP4Linux#26]
Hi there,
i tried to import rew filters into jamesdsp, but it did not imported anything.
I think the file was already in equalizerapo setting, here it is:
```
Filter  1: ON  PK       Fc     274 Hz  Gain  -9.6 dB  Q 5.000
Filter  2: ON  PK       Fc     497 Hz  Gain  -2.3 dB  Q 1.428
Filter  3: ON  PK       Fc    61.9 Hz  Gain  -8.1 dB  Q 5.171
Filter  4: ON  PK       Fc    71.0 Hz  Gain  -8.4 dB  Q 7.014
Filter  5: ON  PK       Fc     394 Hz  Gain  -3.7 dB  Q 5.000
Filter  6: ON  PK       Fc     208 Hz  Gain  -6.4 dB  Q 14.757
Filter  7: ON  PK       Fc     316 Hz  Gain  -3.3 dB  Q 5.000
Filter  8: ON  PK       Fc     355 Hz  Gain   3.0 dB  Q 5.000
Filter  9: ON  PK       Fc     224 Hz  Gain   3.0 dB  Q 5.000
Filter 10: ON  PK       Fc     440 Hz  Gain   3.0 dB  Q 5.000
Filter 11: ON  PK       Fc     224 Hz  Gain   3.0 dB  Q 5.000
Filter 12: ON  PK       Fc     297 Hz  Gain   3.0 dB  Q 5.000
Filter 13: ON  PK       Fc     196 Hz  Gain  -4.4 dB  Q 5.000
Filter 14: ON  PK       Fc    78.2 Hz  Gain  -5.0 dB  Q 12.628
Filter 15: ON  PK       Fc     164 Hz  Gain  -4.5 dB  Q 15.795
Filter 16: ON  PK       Fc    91.9 Hz  Gain  -4.6 dB  Q 23.086
Filter 17: ON  PK       Fc     176 Hz  Gain   3.0 dB  Q 10.711
```
Does it expect some sore of keyword? is it fixable by my side? Thanks!

**Comment by kokoko3k** [comment]
Oh right, i understood that the only parametric equalizer is from the viper part, so i used ddctoolbox to convert from rew to vdc and finally into jamesdsp.
Is this the only way?
Thanks!

**Comment by ThePBone** [comment]
The EqualizerAPO import option in the GraphicEQ section can only parse EqualizerAPO graphic eq settings, not parametric eq settings. There is currently no such option to import parametric eq data in EqualizerAPO format in JamesDSP.


But as you already mentioned, you can use ddctoolbox to import parametric eq settings and create a VDC file. Using ddctoolbox for handling any kind of parametric EQ settings is currently the recommended option.
