### ISSUE TITLE
Always starts maximised

### ISSUE THREAD

**Issue by noodly-poe** [Audio4Linux/JDSP4Linux#27]
Hi, even though I set to start minimised it doesn't happen and the main window always opens when I start my PC.
Using EndeavourOS Plasma.

**Comment by snacksncode** [comment]
Can confirm. Was about to start a new issue but it's already there. More info:
Installed `jamesdsp` (2.3-1) from AUR (pipewire). Also on EndeavourOS, also on KDE Plasma (5.24.1). In autostart command is set to `sleep 5s && /usr/bin/jamesdsp --tray &` so it should start minimized but when system starts it pops up as a window. Any ideas?

**Comment by ThePBone** [comment]
This is an issue with KDE's session management system.
The autostart entry starts JamesDSP minimized in the tray bar correctly; however, KDE attempts to restore/restart all programs that were active before logging out or shutting the PC down. This causes KDE to start JamesDSP a second time without the `--tray` flag, which will display the app window in the foreground.
I've already attempted to detect whether KDE's session manager has launched the app, but I wasn't able to get it working yet.

As a workaround, you could try to exclude JamesDSP from KDE's session restore feature until I find a proper fix for this: 
1. Go to Settings > Startup and Shutdown > Desktop Session
2. Insert `jamesdsp` into the 'don't restore these applications' input field and save the changes

**Comment by ThePBone** [comment]
Commit 377333c2e4ef2c8f280e220195a1d98cc76d7592 fixes this issue
