### ISSUE TITLE
Can't install jamesdsp-pipewire on Kubuntu 20.04

### ISSUE THREAD

**Issue by DementyR** [Audio4Linux/JDSP4Linux#28]
Greetings.

Can't install jamesdsp-pipewire on Kubuntu 20.04. 

`Depends: libarchive but it can't be installed
`

Similar to this [(https://github.com/Audio4Linux/JDSP4Linux/issues/20)], but not jamesdsp-**pulse**,  jamesdsp-p**ipewire**.

**Comment by DementyR** [comment]
Saw it https://github.com/Audio4Linux/JDSP4Linux/issues/20#issuecomment-1015668411. Tried installing with apt. Didn't install, wanted that libarchive. Later it was installed, but did not start,  wanted QT 5.15.

I downloaded the deb manually. Installed. The first time it didn't start. But it worked the second time around.

Thank you.

**Comment by ThePBone** [comment]
The PPA package should have been updated properly now. Run `sudo apt update` before retrying.
