### ISSUE TITLE
can this be built against a new version of glibmm ?

### ISSUE THREAD

**Issue by nixinator** [Audio4Linux/JDSP4Linux#32]
The build currently needs glibmm2.4 

This is very very very old as far as i can see, can the build work against glibmm 2.66.1?

**Comment by ThePBone** [comment]
The glibmm2.4 package name is confusing, it does not actually contain an outdated of glibmm. 

In the package repositories for Ubuntu Focal, the package is currently at version 2.64.2-1 despite the package name, see here: https://packages.ubuntu.com/focal/libglibmm-2.4-dev
