### ISSUE TITLE
Compile from source on Debian 11

### ISSUE THREAD

**Issue by sid-the-sloth** [Audio4Linux/JDSP4Linux#36]
Instructions for compiling from source on Debian 11 (with PulseAudio) state that the package `libgstreamer-plugins-good1.0-dev` should be installed.

But on Debian 11 package `libgstreamer-plugins-good1.0-dev` is not available, as you can see:

```
# apt-cache search libgstreamer
libgstreamer1.0-0 - Core GStreamer libraries and elements
libgstreamer1.0-dev - GStreamer core development files
libgstreamermm-1.0-1 - C++ wrapper library for GStreamer (shared libraries)
libgstreamermm-1.0-dev - C++ wrapper library for GStreamer (development files)
libgstreamermm-1.0-doc - C++ wrapper library for GStreamer (documentation)
libgstreamerd-3-0 - GStreamer media framework - D bindings
libgstreamerd-3-dev - GStreamer media framework - development files for D
libgstreamer-ocaml - OCaml interface to the GStreamer library -- runtime files
libgstreamer-ocaml-dev - OCaml interface to the GStreamer library -- development files
librust-gstreamer-sys-dev - FFI bindings to libgstreamer-1.0 - Rust source code
libgstreamer-opencv1.0-0 - GStreamer OpenCV libraries
libgstreamer-plugins-bad1.0-0 - GStreamer development files for libraries from the "bad" set
libgstreamer-plugins-bad1.0-dev - GStreamer development files for libraries from the "bad" set
libgstreamer-gl1.0-0 - GStreamer GL libraries
libgstreamer-plugins-base1.0-0 - GStreamer libraries from the "base" set
libgstreamer-plugins-base1.0-dev - GStreamer development files for libraries from the "base" set
```

Please advise / alter the instructions to make them compatible with Debian 11.

Thank you.

**Comment by 45bcdf** [comment]
> Instructions for compiling from source on Debian 11 (with PulseAudio) state that the package `libgstreamer-plugins-good1.0-dev` should be installed.
> 
> But on Debian 11 package `libgstreamer-plugins-good1.0-dev` is not available, as you can see:
> 
> ```
> # apt-cache search libgstreamer
> libgstreamer1.0-0 - Core GStreamer libraries and elements
> libgstreamer1.0-dev - GStreamer core development files
> libgstreamermm-1.0-1 - C++ wrapper library for GStreamer (shared libraries)
> libgstreamermm-1.0-dev - C++ wrapper library for GStreamer (development files)
> libgstreamermm-1.0-doc - C++ wrapper library for GStreamer (documentation)
> libgstreamerd-3-0 - GStreamer media framework - D bindings
> libgstreamerd-3-dev - GStreamer media framework - development files for D
> libgstreamer-ocaml - OCaml interface to the GStreamer library -- runtime files
> libgstreamer-ocaml-dev - OCaml interface to the GStreamer library -- development files
> librust-gstreamer-sys-dev - FFI bindings to libgstreamer-1.0 - Rust source code
> libgstreamer-opencv1.0-0 - GStreamer OpenCV libraries
> libgstreamer-plugins-bad1.0-0 - GStreamer development files for libraries from the "bad" set
> libgstreamer-plugins-bad1.0-dev - GStreamer development files for libraries from the "bad" set
> libgstreamer-gl1.0-0 - GStreamer GL libraries
> libgstreamer-plugins-base1.0-0 - GStreamer libraries from the "base" set
> libgstreamer-plugins-base1.0-dev - GStreamer development files for libraries from the "base" set
> ```
> 
> Please advise / alter the instructions to make them compatible with Debian 11.


I was able to compile on my Antix 21 (32 bit) system using  "libgstreamer-plugins-base1.0-dev". Everything seems to work fine and I have not had any crashes so far. Granted I may not be getting the best results since I am not using the "good" library,but I have no idea... That said, it certainly sounds comparable to my other computers running "proper" JDSP4Linux installs.  

NOTE: I am mostly using JDSP4Linux for convolution and parametric eq, so maybe I the "base" library is sufficient based on my use. 

Let me know if you want to know more about my build to see if this might work for you.

**Comment by ThePBone** [comment]
Yes, `libgstreamer-plugins-base1.0-dev` is the correct package.

I already received reports about this a few months back, and I thought I had already fixed this, but I accidentally forgot to update the instructions for some distros.
