### ISSUE TITLE
No actual XDG Base dir support

### ISSUE THREAD

**Issue by etircopyh** [Audio4Linux/JDSP4Linux#37]
At the moment hardcoded absolute paths are being used, instead of XDG base dir specs with relevant overrides/fallbacks (e.g XDG_CONFIG_HOME env variable). [QStandardPaths](https://doc.qt.io/qt-5/qstandardpaths.html) can be used for this purpose.

**Comment by ThePBone** [comment]
Thanks! Commit `aa6729e61e002a756dd04725203e03bfc313d15d` adds proper XDG base dir support.
