### ISSUE TITLE
Unhardcoded tray icon

### ISSUE THREAD

**Issue by varlesh** [Audio4Linux/JDSP4Linux#4]
Will be good use tray icon from theme (if available):
`QIcon::fromTheme("jamesdsp-tray", QIcon(":/icons/icon.png"))`
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2810

**Comment by ThePBone** [comment]
Thanks for pointing that out.
I've pushed the change; the application searches now for the icon key `jamesdsp-tray`. (dbc19d2fb9a1585091a18a2e0ef3717e5b55b27b)
