### ISSUE TITLE
[Feature request] Stereo convolver

### ISSUE THREAD

**Issue by JElfferich** [Audio4Linux/JDSP4Linux#42]
Hello! I really like this program for it's high fidelity sounding DSP. I want to use Joe Bloggs stereo convolver samples but I think this software only supports 1 sample at a time. Do I misunderstand something or is this just a missing feature? Any help would be great!

**Comment by james34602** [comment]
Most convolver software support only one impulse response file at a time.

The length of the impulse response can be arbitrary.
