### ISSUE TITLE
Disable backtrace option support

### ISSUE THREAD

**Issue by leonardohn** [Audio4Linux/JDSP4Linux#44]
I've been trying to create a jamesdsp package for Gentoo, but the package fails to build under musl profile as musl does not implement execinfo.h ([here](https://github.com/Audio4Linux/JDSP4Linux/blob/a11f428284ec6ad3c3cd7336b0bd19304338ac5d/src/crash/stacktrace.h#L7)). Is there any chance of having a configuration to disable backtrace through qmake?

EDIT: I tried to use `DEFINES += AIRBAG_NO_BACKTRACE`, but the aforementioned file is still imported and the error persists.

**Comment by ThePBone** [comment]
Sorry for the delay on this. There's now an option to disable the backtrace library: 
The latest commit adds an option to disable it at compile time. Pull the latest commit and compile this app using these commands:

```bash
qmake ../JDSP4Linux.pro DEFINES+=NO_CRASH_HANDLER
```
