### ISSUE TITLE
MultiChannel

### ISSUE THREAD

**Issue by adolfotregosa** [Audio4Linux/JDSP4Linux#45]
This as been a struggle for me. Multichannel convolver. I can do it using carla but a simple, global dsp would be simpler. 

Is it possible to add ? Specifically I need a way to load my IR for the other channels, not just the fronts. Something that understands .cfg files -> http://convolver.sourceforge.net/config.html and examples http://convolver.sourceforge.net/configegs.html would be freaking awesome.

Thank you

**Comment by james34602** [comment]
The processing pipeline is inherently cannot handle multichannel, although the convolution engine does support multichannel, it just less consistent if part of JDSP support, some part of JDSP doesn't
