### ISSUE TITLE
App doesn't seem to autostart on kde in a Manjaro installation

### ISSUE THREAD

**Issue by clmbtti** [Audio4Linux/JDSP4Linux#49]
Even though there's an entry to JamesDSP for Linux Systray in kde's autostart settings, the application doesn't load automatically. I need to manually load the app from the application launcher. Running jamesdsp -t on terminal doesn't pop any error out.

**Comment by ThePBone** [comment]
I noticed this too on my installation after a recent KDE update. I'll look into it

**Comment by clmbtti** [comment]
I'm under the impression the app might be crashing during or immediately
after the system restarts. To test that, I am using a process monitor
script:
-----
#!/bin/bash

if [[ -z "$1" ]];then
    echo "ERROR: must specify program"
    exit 1
fi

while (( 0 == 0 ));do
    $@ &
    pid=`jobs -l | awk '{print $2}'`
    wait $pid
done
----

I've been running it as a login script to call jamesdsp like
"~/process_monitor.sh jamesdsp -t".
By doing that, I am certain that even if the app eventually crashes, it
will be running again in no time.

**Comment by ThePBone** [comment]
If the app was compiled with crash reporting support (by default), it should write a crash dump into `/tmp/jamesdsp/crash.dmp` and a log to `/tmp/jamesdsp/application.log` . 

Does your workaround fix the issue for you?
Perhaps KDE launches the auto-start apps a bit too early when Pulse or Pipewire are not yet fully ready. If there's no pulse/PW server present, this app will terminate itself and refuse to run at the moment.

**Comment by clmbtti** [comment]
I missed one of the files.

**Comment by Exioncore** [comment]
I am experiencing this same issue on Fedora 36. I just can't get it to start at startup, always have to manually start it.

**Comment by ThiagoSchetini** [comment]
same error here on archlinux. I need to start it manually, when i check the autostart option on configs it register on the "Tweaks" but does not work. There is some crash on dump files but i'm not sure if this crash comes from autostart or not.

**Comment by ThePBone** [comment]
This issue is very likely fixed by https://github.com/Audio4Linux/JDSP4Linux/releases/tag/2.5.0. It adds some additional startup logic that should handle this correctly.
