### ISSUE TITLE
Liveprog crashes

### ISSUE THREAD

**Issue by acarasimon96** [Audio4Linux/JDSP4Linux#5]
I've had the app crash every time I reload JamesDSP from the More menu inside the app while Liveprog is enabled. In addition, JamesDSP would also crash when I enable Liveprog scripts if it was initially disabled at app startup.

**App version:** 2.0 ([PulseAudio build package from AUR](https://aur.archlinux.org/packages/jamesdsp-pulse))
**Distribution:** Manjaro

**Comment by ThePBone** [comment]
Could you please post the .eel file that is being loaded?

You can find out which one is loaded by executing:

	cat ~/.config/jamesdsp/audio.conf | grep liveprog_file

**Comment by acarasimon96** [comment]
Currently, I'm using `stereowide.eel`, which comes bundled with the package. The crash occurs with any Liveprog script I choose, and I don't have any custom EEL files in the liveprog directory at the moment.

[crash.dmp](https://github.com/Audio4Linux/JDSP4Linux/files/7179227/crash.dmp.txt)

[application.log](https://github.com/Audio4Linux/JDSP4Linux/files/7179220/application.log)

**Comment by ThePBone** [comment]
Could you also upload the jamesdsp binary that was compiled by the AUR package?

It is located at `/usr/bin/jamesdsp` in your case. The backtrace in the crash dump only contains the hex addresses to code segments in the binary and not any human-readable information, so I'll need to look these addresses up manually.

**Comment by acarasimon96** [comment]
I can't upload it here on GitHub, unfortunately. You could, however, spin up a virtual machine with Arch or Manjaro if you don't use it and do your debugging from there.

**Comment by ThePBone** [comment]
I still had 2.0 from the AUR in the cache, so I could have used that one. However, these memory offsets differ between each compilation, even when compiling the exact same code. 

Anyway, I can reproduce your issue on my Ubuntu VM which is running PulseAudio as well. 
I'll have a look at it, this way I can start debugging it right away.

**Comment by ThePBone** [comment]
Fixed with commit 4e69e307115c1aca77f27d13ab879d1947149d05. You can use the -git AUR package if you need an update right away.

**Comment by acarasimon96** [comment]
Thanks for the speedy fix! I was able to confirm that the crashes have stopped, but I also ran into another bug related to enabling/disabling Liveprog scripts, which I will report in a separate issue.
