### ISSUE TITLE
NO_PUBKEY 0E7DFE0CFBEFBBA6

### ISSUE THREAD

**Issue by Lowrida** [Audio4Linux/JDSP4Linux#51]
When i want to add the PPA i get errors!
GPG error, no signed public key, not safe, updating from this repository is turned off.

I could include the exact errors, but they are in Dutch.

**Comment by Lowrida** [comment]
Never mind, i went for something else..

**Comment by ThePBone** [comment]
If anyone else happens to run into this issue, add the key manually from a keyserver:
```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv-keys 0E7DFE0CFBEFBBA6
```
Normally, the key should have been imported when adding the PPA to apt:
```
curl -s --compressed "https://thepbone.github.io/PPA-Repository/KEY.gpg" | sudo apt-key add -
```
