### ISSUE TITLE
Application saving its geometry settings to "~/.config/Unknown Organization"

### ISSUE THREAD

**Issue by dr460nf1r3** [Audio4Linux/JDSP4Linux#52]
Current behaviour: geometry settings are saved in `~/.config/Unknown Organization`, the rest of the settings are correctly retained in `~/.config/jamesdsp`. 
Expected behaviour: every setting is saved in `~/.config/jamesdsp`

![image](https://user-images.githubusercontent.com/12834713/168466545-154fa19e-0be3-44c0-8c20-3b818da52f5c.png)

**Comment by ThePBone** [comment]
This issue has already been fixed, see #24

**Comment by dr460nf1r3** [comment]
Oh haha, I just found this when going through my config files. Good to know and great work on the application! :)
