### ISSUE TITLE
App crashes (?) / doesn't reopen on KDE after lock & relogin

### ISSUE THREAD

**Issue by snacksncode** [Audio4Linux/JDSP4Linux#54]
Hi, I posted an issue quite some time back about app starting not-minimized on KDE. I think there was a patch pushed to fix that but for me it's still the same. It's not a really big deal, just close the app it stays minimized and works. But I've noticed that after locking KDE and logging back it the app kinda disappears. I don't think it's crashing but it's a possibility. I think it has something to do with KDE reopening apps after re-login and it ignores JDSP. Any ideas? Any more info I can give to help identify the issue?

**Comment by ThePBone** [comment]
https://github.com/Audio4Linux/JDSP4Linux/releases/tag/2.5.0 contains another related fix that prevents this properly.
