### ISSUE TITLE
How does the convolver handle different sample rates?

### ISSUE THREAD

**Issue by pinbuck** [Audio4Linux/JDSP4Linux#57]
Let's say by default I use 44100hz as primary, with both 44100hz and 48000hz allowed in pipewire config, the latter for 48000hz audio sources like videogames, 44100hz being the most common for audio (or so i've read and seen)

Does the convolver do the same thing that easyeffects does? It would be cool if you could load both of them at the same time, and it would automatically assign the correct convolution file based on the audio source's sample rate to reduce processing time.

Similar question found in EasyEffects:
https://github.com/wwmm/easyeffects/discussions/930

**Comment by ThePBone** [comment]
Yes, the convolver does the same thing that easyeffects does. 

If the sampling rate of the impulse response does not match the system sampling rate, it will automatically be resampled once when loaded. It shouldn't add any processing time because it is just done once.
