### ISSUE TITLE
Application whitelist is cleared/mangled on JamesDSP startup

### ISSUE THREAD

**Issue by kokoko3k** [Audio4Linux/JDSP4Linux#58]
this is my application.conf before closing:
```
AudioAppBlocklist=;effect_output.virtual-surround-5.1-hesuvi;effect_output.virtual-surround-7.1-hesuvi
AudioAppBlocklistInvert=true
AudioOutputDevice=alsa_output.pci-0000_00_1f.3.analog-stereo
AudioOutputUseDefault=false
ExecutablePath=/usr/bin/jamesdsp
SendCrashReports=true
SetupDone=true
TrayIconMenu=passthrough;menu_preset;separator;show;quit;
```
This is after i restart it:
```
AudioAppBlocklist=
AudioAppBlocklistInvert=true
AudioOutputDevice=alsa_output.pci-0000_00_1f.3.analog-stereo
AudioOutputUseDefault=false
ExecutablePath=/usr/bin/jamesdsp
SendCrashReports=true
SetupDone=true
TrayIconMenu=passthrough;menu_preset;separator;show;quit;
````

I din't do anything to jamesdsp config, just quitting and reopening it is sufficient for it to clear AudioAppBlocklist.
It is something it does when it starts, because application.conf is still correct  before starting jamesdsp.
I'm using version 2.3-3 ; the feature is very important to me, because that virtual surround pipewire sinks as the default ones through kde plasma, and i want jamesdsp to further process his stereo output by default.
Thanks!

**Comment by ThePBone** [comment]
I think I already fixed this, but I'm not entirely sure.

It looks like you're currently using the latest stable release. Try the latest unstable package, which includes some improvements for the whitelist. 

If you're on Ubuntu using the PPA packages, you can grab a precompiled package here: https://github.com/Audio4Linux/JDSP4Linux/actions/runs/2569293697
Just install it with `dpkg` over the stable version.

On Arch, there's the `jamesdsp-git` package that includes the latest changes.

**Comment by kokoko3k** [comment]
Yeah, thanks.
Just compiled the latest git on aur, it seems it works as intended now.
