### ISSUE TITLE
Liveprog stays enabled when reloading DSP or switching presets

### ISSUE THREAD

**Issue by acarasimon96** [Audio4Linux/JDSP4Linux#6]
While I successfully tested the fix for #5, I've noticed that Liveprog remains enabled when I switch between presets or reloaded the DSP via the app menu. In my scenario, I have a preset with Liveprog turned on and another without it. I can also reproduce this behavior when I enable Liveprog without a preset loaded before reloading the DSP or loading another preset.

**App version:** Git ([PulseAudio package from AUR](https://aur.archlinux.org/packages/jamesdsp-pulse-git)). Note that this can also be reproduced in version 2.0 and 2.1
**Distribution:** Manjaro

**Comment by ThePBone** [comment]
I think I found the issue:
```
[16:19:50.726] [DBG] DspHost::refreshLiveprog: Referenced file does not exist anymore. Cannot reload.
```

When no liveprog file is set (or it isn't accessible), the refreshLiveprog() returns prematurely without applying any configuration updates for the liveprog module => the enable flag is not modified.

Anyway, commit 6bbea42680f2f1e6872e1d01756b09c3d6f716de fixes this.
Thanks for reporting it
