### ISSUE TITLE
Crash build

### ISSUE THREAD

**Issue by SergeyDjam** [Audio4Linux/JDSP4Linux#63]
```
In file included from ../../src/audio/base/DspHost.cpp:6:0:
../../src/audio/base/DspHost.h:5:15: fatal error: any: No such file or directory
compilation terminated.
```
https://github.com/Audio4Linux/JDSP4Linux/blob/c8dd888ed1cd30ea8a5153bb265d1e7ee2b181f2/src/audio/base/DspHost.h#L5

version 2.3

ROSA Fresh 2016.1
Qt5 5.11.2
kernel 5.13.9-generic-1rosa-x86_64
pulseaudio 12.2

``` shell
mkdir build
cd build
qmake-qt5 ../JDSP4Linux.pro "CONFIG += USE_PULSEAUDIO"
```

**Comment by SergeyDjam** [comment]
how fix it?

**Comment by ThePBone** [comment]
Hey,
Your compiler appears to be too old. This application requires a compiler that is compliant with the C++17 standard. This standard also provides the missing `any` header file.

**Comment by SergeyDjam** [comment]
Hm, ok, thx

**Comment by SergeyDjam** [comment]
Can i use clang/llvm for build?

**Comment by SergeyDjam** [comment]
```bash
qmake_qt5 ../JDSP4Linux.pro \
           "CONFIG += USE_PULSEAUDIO" \
           "QMAKE_CXX = clang++" \
           "QMAKE_LINK = clang++" \
           "QMAKE_CXXFLAGS -= -fvar-tracking-assignments" \
           "QMAKE_CC = clang" \
           "QMAKE_CFLAGS -= -fvar-tracking-assignments"
```

clang-12: error: unknown argument: '-fvar-tracking-assignments'
clang-12: error: unknown argument: '-fvar-tracking-assignments'
clang-12: error: unknown argument: '-fvar-tracking-assignments'
make[1]: *** [Makefile:529: bs2b.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:563: crossfeed.o] Error 1
make[1]: *** [Makefile:580: dbb.o] Error 1
clang-12: error: unknown argument: '-fvar-tracking-assignments'
clang-12: error: unknown argument: '-fvar-tracking-assignments'
clang-12: error: unknown argument: '-fvar-tracking-assignments'
make[1]: *** [Makefile:546: convolver1D.o] Error 1
make[1]: *** [Makefile:599: dynamic.o] Error 1
make[1]: *** [Makefile:512: arbEqConv.o] Error 1
clang-12: error: unknown argument: '-fvar-tracking-assignments'
clang-12: error: unknown argument: '-fvar-tracking-assignments'
make[1]: *** [Makefile:610: fft.o] Error 1
make[1]: *** [Makefile:602: cpthread.o] Error 1
make[1]: Leaving directory '/home/builder/rpmbuild/BUILD/JDSP4Linux-2.3/build/libjamesdsp'
make: *** [Makefile:46: sub-libjamesdsp-make_first] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.77216 (%build)

**Comment by SergeyDjam** [comment]
"QMAKE_CFLAGS -= -fvar-tracking-assignments" not work :(
