### ISSUE TITLE
Wrong icon link

### ISSUE THREAD

**Issue by Crylia** [Audio4Linux/JDSP4Linux#67]
`sudo wget -O /usr/share/pixmaps/jamesdsp.png https://raw.githubusercontent.com/Audio4Linux/JDSP4Linux-GUI/master/resources/icons/icon.png -q --show-progress`

needs to be 

`sudo wget -O /usr/share/pixmaps/jamesdsp.png https://raw.githubusercontent.com/Audio4Linux/JDSP4Linux/master/resources/icons/icon.png -q --show-progress`

**Comment by ThePBone** [comment]
Thanks! Fixed it.
