### ISSUE TITLE
Issues regarding Qt library

### ISSUE THREAD

**Issue by carlostapella** [Audio4Linux/JDSP4Linux#7]
Hi.
I am a Linux Mint 20.2 user. When i try to lounch the software via terminal I get the following message:

jamesdsp: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by jamesdsp)

How can I fix it?

Thank you for your help.

**Comment by ThePBone** [comment]
Did you use the Qt online installer to install Qt 5.15 and compile this app with it?

If yes, you need to tell the app where the installer placed Qt 5.15 (it doesn't place it into the default library search path of your system).

You can do this by setting the `LD_LIBRARY_PATH` environment variable:

```
export LD_LIBRARY_PATH="/home/user/Qt/5.15/gcc_64" 
```
^ something like this

**Comment by carlostapella** [comment]
Hi
Not working on Linux Mint 20.2 xfce (based Ubuntu 20.04)
Thanks
