### ISSUE TITLE
Issues with new versions of WirePlumber

### ISSUE THREAD

**Issue by HanabishiRecca** [Audio4Linux/JDSP4Linux#70]
_The issue appeard some time ago, but I get my hands on it only now._  

JDSP doesn't work properly with new versions of WirePlumber. Seems like it loses the sink every time session being destroyed (e.g. on inactvity). "JamesDSP Sink" becames "Unknown output", audio doesn't work and I got errors from WirePlumber:
```
wireplumber[958]: <WpSiStandardLink:0x7faf84006a60> Link was not activated before removing
wireplumber[958]: <WpSiStandardLink:0x7faf84006a60> Failed to create links because of wrong ports
```
Seems like it is related to changes made by [this merge request](https://gitlab.freedesktop.org/pipewire/wireplumber/-/merge_requests/398). Changes was not yet released, but Arch Linux `wireplumber` package [adopted it as a patch](https://github.com/archlinux/svntogit-packages/commit/2e21a3240aa3a7c96c523441f28e1f800699482b) before the actual release, so this is why I already facing it.
Obviously more people from other distros will face it in the future.

**Comment by ThePBone** [comment]
Thanks for the details! I noticed this issue too for some time (especially when re-connecting my Bluetooth headphones), but I didn't have time to investigate it.

I've pushed a new commit that fixes the issue for me. Could you please test if it fixes the problem for you too?
