### ISSUE TITLE
JamesDSP running but SingleInstanceMonitor::isServiceReady: Service registration failed. Name already aquired by other instance - XFCE

### ISSUE THREAD

**Issue by artofit** [Audio4Linux/JDSP4Linux#72]
In view of https://github.com/Audio4Linux/JDSP4Linux/issues/49

there might be a bug in JamesDSP under Manjaro, see
https://forum.manjaro.org/t/jamesdsp-running-but-no-hearable-effects-xfce/123330

**Comment by ThePBone** [comment]
Hi, the log output you posted in the forum indicates that you are using the default Pipewire flavor (AUR packages are named `jamesdsp` or `jamesdsp-git`) even though your system is running Pulseaudio. 
You can fix this by installing `jamesdsp-pulse` instead.
