### ISSUE TITLE
JamesDSP prevents video playback until volume/audio button is clicked

### ISSUE THREAD

**Issue by jastx-jasmint** [Audio4Linux/JDSP4Linux#74]
Hello, it appears that this has not been reported here despite it being quite a notorious issue ([here's one such thread on the Garuda Linux forums](https://forum.garudalinux.org/t/youtube-video-doesnt-play-until-volume-icon-is-clicked/22800/1)). 

This issue doesn't discriminate against browsers, and tends to randomly appear. It affects any form of video playback in the system, which means VLC and other media playback apps are affected as well. Many have solved the issue by not letting JamesDSP autostart, but the issue is that when it is started, it will sometimes exhibit this problem. It appears that once it happens during a session, it will always happen upon a restart of the program. It's not always guaranteed that the issue happens as soon as JamesDSP is autostarted- as is often in my case, it just randomly happens when it feels like it.

When this issue happens, Firefox and Chromium will suggest restarting the device. Clicking the volume icon, adjusting the volume or quitting JamesDSP will unfreeze the video, but skipping through the video will cause it to freeze again until one of the actions mentioned are taken (except for the quit one).
I love using JamesDSP for its bass boost, so I would prefer not to disable autostart or fiddle with volume buttons.

Here's my system information to help you troubleshoot, though this hasn't been limited to only one person or system: https://gist.github.com/jastx-jasmint/e0f9b61e6e70086bfed77f99cd3dddfe

**Comment by wwmm** [comment]
>The pipewire backend of this app is closely based on EasyEffects' implementation, so it is a good idea to keep an eye on the issues in their repo too.

>I couldn't find anything relevant in pipewire's or jamesdsp's log yet. I'll probably search through the changelogs for wireplumber and pipewire, maybe there were some breaking changes I missed.

I have tried to debug this in EasyEffects several times.. If this is the same bug we are seeing on our side just looking at PipeWire's logs is useless. We have to find a reliable way to make it happen so we look at PipeWire's logs at the moment the bug manifest itself. But even after many months I could not find a way.

A long time ago I opened an issue about this in PipeWire's page. The main problem is that according to PipeWire's own tools like pw-dot everything is fine. The links are there and active. Things should work fine... But somehow they doesn't...

**Comment by jastx-jasmint** [comment]
> It has been reported earlier: https://github.com/Audio4Linux/JDSP4Linux/issues/70
Ahh I didn't see it as I only looked at open issues, sorry about that. ^^;

Awesome that you've come up with a hotfix! I'll give it a try, and close the issue if it fixes it.

**Comment by jastx-jasmint** [comment]
> I don't think it should be closed now. At least for people to see the problem exists.

Ahh yep, understood, since that was my same exact misunderstanding HAHA
I didn't expect this to get addressed so quickly, so this is really epic. Thank you for moving this along and bringing it to the attention of the right people. :D

**Comment by jastx-jasmint** [comment]
Ohh, interesting :O

**Comment by jastx-jasmint** [comment]
This hasn't been an issue since the update, which is awesome :D 
Shall I close the issue?

**Comment by HanabishiRecca** [comment]
Which update? There were no updates for JDSP or WirePlumber since.

**Comment by jastx-jasmint** [comment]
Since the merge request you linked before, which got merged into the master branch. I haven't encountered the issue mentioned in this thread since then

**Comment by HanabishiRecca** [comment]
Are you using [`wireplumber`](https://archlinux.org/packages/extra/x86_64/wireplumber/) package from Arch repo?
```
Last Updated: 2022-10-07 18:32 UTC
```
If you did not applied hotfix manually, this is magic.

**Comment by ThePBone** [comment]
Probably [`wireplumber-git`](https://aur.archlinux.org/packages/wireplumber-git) from the AUR? It works flawlessly for me so far.

**Comment by jastx-jasmint** [comment]
bruh sorry all, did the dumb haha. I applied the hotfix manually, so of course it'd work 🤡  I'm not using `wireplumber-git`, but if I ever magically run into the issue again, I'll give it a shot.

**Comment by jastx-jasmint** [comment]
Awesome ^^ is it time to close this issue?

**Comment by HanabishiRecca** [comment]
If it solves the issue for you, I think yes.

**Comment by zany130** [comment]
I'm still having this issue in all apps now originally it was only in proton games.

**Comment by LOLCATATONIA** [comment]
Also having this issue... also using Garuda. How can I assist in solving the problem?

**Comment by HanabishiRecca** [comment]
> Also having this issue... also using Garuda

WirePlumber 0.4.13? I have no issues on Arch after the update (as expected). AFAIK Garuda uses Arch repos for packages so should behave the same.

Anyway, inspect your system logs. There can be unrelated problems. Generally collect
```
$ journalctl --user-unit=pipewire.service
$ journalctl --user-unit=pipewire-pulse.service
$ journalctl --user-unit=wireplumber.service
```
after the problem appears.

**Comment by zany130** [comment]
```
journalctl --user-unit=wireplumber.service
Dec 16 22:48:49 Garuda-Linux wireplumber[105494]: <WpPortalPermissionStorePlugin:0x55e3d2b10f20> Fai>
Dec 17 02:39:46 Garuda-Linux systemd[104869]: Stopping Multimedia Service Session Manager...
Dec 17 02:39:46 Garuda-Linux wireplumber[105494]: stopped by signal: Terminated
Dec 17 02:39:46 Garuda-Linux wireplumber[105494]: disconnected from pipewire
Dec 17 02:39:46 Garuda-Linux systemd[104869]: Stopped Multimedia Service Session Manager.
Dec 17 02:39:46 Garuda-Linux systemd[104869]: wireplumber.service: Consumed 4.597s CPU time.
-- Boot 73e037fdea07491d8af47560fd923814 --
Dec 17 12:04:35 Garuda-Linux systemd[10377]: Started Multimedia Service Session Manager.
Dec 17 12:04:35 Garuda-Linux wireplumber[10980]: [0:00:19.103731216] [10980]  INFO Camera camera_man>
Dec 17 12:04:36 Garuda-Linux wireplumber[10980]: <WpPortalPermissionStorePlugin:0x55c3e0c6f220> Fail>
lines 1-10/10 (END)
```

```
journalctl --user-unit=pipewire.service
Dec 16 20:20:44 Garuda-Linux pipewire[105492]: mod.x11-bell: X11 I/O error handler called on display>
Dec 16 20:20:44 Garuda-Linux pipewire[105492]: mod.x11-bell: X11 display (:1) has encountered a fata>
Dec 17 02:39:46 Garuda-Linux systemd[104869]: Stopping PipeWire Multimedia Service...
Dec 17 02:39:46 Garuda-Linux systemd[104869]: Stopped PipeWire Multimedia Service.
Dec 17 02:39:46 Garuda-Linux systemd[104869]: pipewire.service: Consumed 1min 46.102s CPU time.
-- Boot 73e037fdea07491d8af47560fd923814 --
Dec 17 12:04:35 Garuda-Linux systemd[10377]: Started PipeWire Multimedia Service.
lines 1-7/7 (END)...skipping...
Dec 16 20:20:44 Garuda-Linux pipewire[105492]: mod.x11-bell: X11 I/O error handler called on display>
Dec 16 20:20:44 Garuda-Linux pipewire[105492]: mod.x11-bell: X11 display (:1) has encountered a fata>
Dec 17 02:39:46 Garuda-Linux systemd[104869]: Stopping PipeWire Multimedia Service...
Dec 17 02:39:46 Garuda-Linux systemd[104869]: Stopped PipeWire Multimedia Service.
Dec 17 02:39:46 Garuda-Linux systemd[104869]: pipewire.service: Consumed 1min 46.102s CPU time.
-- Boot 73e037fdea07491d8af47560fd923814 --
Dec 17 12:04:35 Garuda-Linux systemd[10377]: Started PipeWire Multimedia Service.
```
```
journalctl --user-unit=pipewire-pulse.service
Dec 17 02:39:46 Garuda-Linux systemd[104869]: Stopping PipeWire PulseAudio...
Dec 17 02:39:46 Garuda-Linux systemd[104869]: Stopped PipeWire PulseAudio.
Dec 17 02:39:46 Garuda-Linux systemd[104869]: pipewire-pulse.service: Consumed 3min 12.110s CPU time.
-- Boot 73e037fdea07491d8af47560fd923814 --
Dec 17 12:04:37 Garuda-Linux systemd[10377]: Started PipeWire PulseAudio.
```
thats what it shows for me

**Comment by HanabishiRecca** [comment]
@zany130 seems like you have some issues `wireplumber[10980]: <WpPortalPermissionStorePlugin:0x55c3e0c6f220> Fail>` but your log is abrupted. Use something like
```
$ journalctl --user-unit=wireplumber.service --no-pager
```
or just pipe it to a file, e.g.
```
$ journalctl --user-unit=wireplumber.service > wireplumber.log
```

**Comment by zany130** [comment]
Those errors seems to be due to screen sharing as they pop up whenever I use discord screen share or launch obs so I don't think its related to this issue. Audio continues to work when those errors show up anyway, in fact nothing new is logged in the journal when I launch jamesdsp and immediately lose audio

**Comment by HanabishiRecca** [comment]
> I launch jamesdsp and immediately lose audio

Hmm, are you sure your audio setup is ok? Did you checked it with something like `pavucontrol`?
Like proper output should be selected as the default. Your real one, not JamesDSP Sink.
Also JamesDSP Sink should not be muted. And its monitor (input device) too.

**Comment by HanabishiRecca** [comment]
> are you sure your audio setup is ok?

But now reading your original issue, I don't think this is the case.

I see there are USB/Bluetooth audio devices in your system. The problem appears when you use them? Did you tried wired output?

**Comment by zany130** [comment]
> Also JamesDSP Sink should not be muted. And its monitor (input device) too.

Well that was exactly the issue :facepalm:  unmuted it and now everything seems to be working

**Comment by ThePBone** [comment]
> Well that was exactly the issue unmuted it and now everything seems to be working

Great! I'll see if I can implement a check that ensures that the sink is unmuted at all times.
