### ISSUE TITLE
james looses pipeline on pause

### ISSUE THREAD

**Issue by trackhacs** [Audio4Linux/JDSP4Linux#81]
manjaro - pulse

james 2.4-1

Every time here is a pause between songs james loosed pipeline and pipeline goes quite. need to manually "relink audio pipeline" - which is ofc quite unconformable.

any solution to prevent that?

**Comment by ThePBone** [comment]
Try to update to the latest git version (use `jamesdsp-git` package). It has better compatibility with newer wireplumber versions and should have fixed this issue.

See also https://github.com/Audio4Linux/JDSP4Linux/issues/74
