### ISSUE TITLE
Update url of `LiveprogIDE` submodule

### ISSUE THREAD

**Issue by HanabishiRecca** [Audio4Linux/JDSP4Linux#82]
`EELEditor` repo was renamed into `LiveprogIDE` at some point.
But in `.gitmodules` it is still referenced by old url.

https://github.com/Audio4Linux/JDSP4Linux/blob/e2c5addc77ebb15dbda4244ca9c22f977daeb32d/.gitmodules#L3

GitHub seems to be fine with it now, but it may cause issues in the future.

**Comment by ThePBone** [comment]
Fixed with commit cb140e5ef20f0458f4b93c2e2e7570fb016e3a75

**Comment by HanabishiRecca** [comment]
Are you sure you've done it right? Current state looks strange.

**Comment by ThePBone** [comment]
Compiles & clones for me correctly.
Only the URL has been updated. The local checkout path for the submodule is still `src/subprojects/EELEditor` to avoid breaking compatibility with the AUR package.

**Comment by HanabishiRecca** [comment]
I mean, look in the file. Also [GitHub interface](https://github.com/Audio4Linux/JDSP4Linux/tree/master/src/subprojects) still points to old url.

**Comment by HanabishiRecca** [comment]
Sorry for issuing to so much trouble with it, but fine now. 👍
